

service: chefbackend 



provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2

functions:
  tasks:
    handler: dining.handler
    events:
      - http:
          path: chefs
          method: get
          cors: true
# this is a plug-in we installed to help us run our API off-line for testing development work
plugins:
  - serverless-offline

